import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomBytes } from 'node:crypto';
import { startGarden } from './helper.mjs';

test('remote MCP OAuth: consent, PKCE, refresh, audience and revocation', { timeout: 20000 }, async t => {
  const publicBase = 'https://garden.example.com';
  const g = await startGarden(t, { publicBase });
  const metadata = await (await g.request('/.well-known/oauth-authorization-server')).json();
  assert.equal(metadata.issuer, publicBase + '/');
  const protectedInfo = await (await g.request('/.well-known/oauth-protected-resource/mcp')).json();
  assert.equal(protectedInfo.resource, publicBase + '/mcp');
  const unauth = await g.json('/mcp', { jsonrpc:'2.0',id:1,method:'tools/list' });
  assert.equal(unauth.status,401); assert.match(unauth.headers.get('www-authenticate'), /resource_metadata=/);
  const redirect = 'https://client.example.com/callback';
  const bad = await g.json('/register', { redirect_uris:['http://unsafe.example.com/callback'],token_endpoint_auth_method:'none' }); assert.equal(bad.status,400);
  const registered = await g.json('/register', { client_name:'Integration test',redirect_uris:[redirect],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code'] });
  assert.equal(registered.status,201); const client = await registered.json();
  const verifier = randomBytes(32).toString('base64url');
  const challenge = createHash('sha256').update(verifier).digest('base64url');
  const params = new URLSearchParams({client_id:client.client_id,redirect_uri:redirect,response_type:'code',code_challenge:challenge,code_challenge_method:'S256',scope:'garden:play',state:'test-state',resource:publicBase+'/mcp'});
  const auth = await g.request('/authorize?' + params); assert.equal(auth.status,200);
  const page = await auth.text(); assert.ok(!page.includes(g.keys.user)); assert.ok(!page.includes(g.keys.ai));
  const transaction = /name="transaction" value="([^"]+)"/.exec(page)?.[1]; assert.ok(transaction);
  const cookie = auth.headers.get('set-cookie').split(';')[0];
  const form = (path, body, headers = {}) => g.request(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',...headers},body:new URLSearchParams(body).toString()});
  const approval = {transaction,key:g.keys.user,decision:'approve'};
  assert.equal((await form('/oauth/approve',approval,{Origin:publicBase})).status,403);
  assert.equal((await form('/oauth/approve',approval,{Origin:'https://evil.example',Cookie:cookie})).status,403);
  const consent = await form('/oauth/approve',approval,{Origin:publicBase,Cookie:cookie}); assert.equal(consent.status,303);
  const location = new URL(consent.headers.get('location')); assert.equal(location.origin,'https://client.example.com'); assert.equal(location.searchParams.get('state'),'test-state');
  const tokenForm = {grant_type:'authorization_code',client_id:client.client_id,code:location.searchParams.get('code'),redirect_uri:redirect,code_verifier:verifier,resource:publicBase+'/mcp'};
  assert.equal((await form('/token',{...tokenForm,code_verifier:'incorrect-verifier'})).status,400);
  assert.equal((await form('/token',{...tokenForm,resource:'https://other.example/mcp'})).status,400);
  const exchanged = await form('/token',tokenForm); assert.equal(exchanged.status,200); const tokens = await exchanged.json();
  assert.equal((await form('/token',tokenForm)).status,400);
  const mcp = token => g.json('/mcp',{jsonrpc:'2.0',id:1,method:'tools/list'},token,{Accept:'application/json, text/event-stream'});
  assert.equal((await mcp(tokens.access_token)).status,200);
  assert.equal((await g.json('/garden/api/connection',undefined,tokens.access_token)).status,401);
  await g.restart();
  assert.equal((await mcp(tokens.access_token)).status,200);
  const refreshForm={grant_type:'refresh_token',client_id:client.client_id,refresh_token:tokens.refresh_token,resource:publicBase+'/mcp'};
  const refreshed=await form('/token',refreshForm); assert.equal(refreshed.status,200); const next=await refreshed.json();
  assert.equal((await form('/token',refreshForm)).status,400);
  assert.equal((await form('/revoke',{client_id:client.client_id,token:next.refresh_token})).status,200);
  assert.equal((await mcp(next.access_token)).status,401); assert.equal((await mcp(tokens.access_token)).status,401);
});
